name = "ai-runner-frontend"
main = "src/index.ts"
compatibility_date = "2025-10-16"

[build]
command = "npm install && npm run build"

# Tell Cloudflare where to find your built frontend
pages_build_output_dir = "dist"

# Environment variables for Supabase
[vars]
VITE_SUPABASE_URL = "https://pjdittwhsvugbcdpmqnj.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
